### ISSUE TITLE
Missing index.html

### ISSUE THREAD

**Issue by TrippyZ** [365businessdev/alget#1]
When I do ALGet:Managage packages I get the following error window;
![image](https://github.com/user-attachments/assets/90a7f735-6524-4bd7-ad1e-4bea16b76ce7)

I have examined the contents the the extension directories and cannot locate and index.html

**Comment by sirhc101** [comment]
Hi @TrippyZ 

Thanks for reporting this issue. Please update to version 0.0.3, there it should be fixed.

~Chris
