### ISSUE TITLE
Download to .alpackages does not remove or replace illegal characters

### ISSUE THREAD

**Issue by geschwint** [365businessdev/alget#2]
If I try to download the app for "Progressus Advanced Projects | EMEA & APAC" it fails to save the data as the app name contains a "|" pipe and that is illegal in a filename. It should be replaced with something legal or just removed.

![2024-11-04_16-21-50](https://github.com/user-attachments/assets/374c00b7-4fbd-468f-8c59-2b447cf075a2)

**Comment by sirhc101** [comment]
Thank you @geschwint for reporting this issue.

I fixed it and will release the update tomorrow with some other enhancements.
![image](https://github.com/user-attachments/assets/5a8a44a2-3359-497b-80b0-3528d790be29)

**Comment by sirhc101** [comment]
Fixed with version 0.0.4
