### ISSUE TITLE
Add Support for Folder Settings - e.g. 

### ISSUE THREAD

**Issue by pri-kise** [365businessdev/alget#4]
It would be useful to specify some settings on a folder settings.json file.

Currently most of our settings are set in the `settings.json` of the specific app.

It would be usefult if we can specify the `365businessdev.alget.countryCode` in the settings.json of a specific app.

We have customers with different country code and it would be useful to keep this information in the app folder.

Is there any reason to not support this?

**Comment by sirhc101** [comment]
Thank you for your feedback. Actually, I need to look into this, as I expected folder settings should already work. Normally I work with workspace settings, but I will check what's wrong

**Comment by sirhc101** [comment]
Fixed with version 0.0.4
